# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

# Strict checks in place
warnings_are_errors: true

branches:
  only:
    - master

repos:
  CRAN: http://cran.dcc.fc.up.pt/

r_packages:
  - knitr
  - rmarkdown
  - remotes
  - utils

# Test code coverage
r_github_packages:
  - jimhester/covr

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
