# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - release
  - bioc-devel
  - bioc-release

# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master

# Run binary install of testthat
r_binary_packages:
  - testthat

r_packages:
  - knitr
  - rmarkdown
  - remotes
  - utils

bioc_packages:
  - BiocVersion
  - BiocStyle

# Test code coverage
r_github_packages:
  - jimhester/covr

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
